### ISSUE TITLE
Adding feature which can download the iflow as zip file. 

### ISSUE THREAD

**Issue by itstushar22** [engswee/flashpipe-action#1]
![image](https://github.com/engswee/flashpipe-action/assets/59661310/a124ca82-c705-4133-bcac-0e8926d09640)

Adding feature which can download the iflow as zip file. This is already part of snapshot step but it willl help if it can be added as individual action feature

**Comment by engswee** [comment]
@itstushar22 - could you elaborate on your use case? What is the zip file subsequently used for?

**Comment by itstushar22** [comment]
@engswee  Like CPI linting.

**Comment by engswee** [comment]
@itstushar22 - understood. You can add steps in your pipeline to zip the content before running cpilint. Personally, I don't see any value in committing the zip file into the Git repo
